// Hassan Uraizee and Travis Juntara
// Color Picker javascript project

// Chosen Color
var theColor = new Color();
// User Color Input textfield
var $colorName;
// Slider Controls
var $R;
var $G;
var $B;
var $H;
var $S;
var $L;
// Auto-Generated Colors
var triLeft = new Color();
var triRight = new Color();
var lighter = new Color();
var darker = new Color();

$(document).ready(function(){
	$colorName = $('#sidebar input');
	sliders();
	$('#hue').slider({
	    max: 360
	});
	setColor();
	fillColor();
	$colorName.change(setColor);
	$('#sidebar, #headd').hover(collapse, disperse);
	$('#chosen').click(collapse);
} );

function inject () {
	/*The inject function is crucial for injecting the chosen colors (and the shades, neigbhoring colors that come with it)
to the preview on the bottom of the page. It modifys the objects css properties.
*/
	$("#sitePreview header").css({"background-color": "white", "color": triRight.hex });	
	
	$("#sitePreview section").css({"background-color": "white", "color": theColor.hex});	
	$("#sitePreview footer").css({"background-color": "silver", "color": darker.hex });	
	$("#sitePreview aside").css({"background-color": triLeft.hex, "color": "white"});	
	$(".circles").css({"background-color": lighter.hex});
	$(".uno").css({"background-color": lighter.hex});
	$(".dos").css({"background-color": triLeft.hex});
	$(".tres").css({"background-color": triRight.hex});

}

function disperse() {
	/* The purpose of this function is to "disperse" the boxes representing the different shades and colors 
stacked behind the chosen color box to their respective locations.
*/	// Displayed Colors Animation command
	$("#darker").css({"margin-top": "280px", "margin-left": "270px"});
	$("#lighter").css({"margin-top": "40px", "margin-left": "270px"});
	$("#triLeft").css({"margin-top": "160px", "margin-left": "150px"});
	$("#triRight").css({"margin-top": "160px", "margin-left": "390px"});
}

function collapse() {
	$("#darker, #lighter, #triLeft, #triRight").css({"margin-top": "", "margin-left": ""});
}

function sliders() {
    // setup color sliders
    $( "#hsl > span" ).each(function() {
        // read initial values from markup and remove that
        var value = parseInt( $( this ).text(), 10 );
        $( this ).empty().slider({
            value: value,
			min: 0,
			max: 100,
            animate: true,
            orientation: "vertical",
	    stop: function(event, ui) {
		 setHSL();
	    }
        });
    });
    $( "#rgb > span" ).each(function() {
        // read initial values from markup and remove that
        var value = parseInt( $( this ).text(), 10 );
        $( this ).empty().slider({
            value: value,
            min: 0,
			max: 255,
            animate: true,
            orientation: "horizontal",
	    stop: function(event, ui){
	      setRGB();
	    }
        });
    });
	//Set Slider's Global DOM Variables
	$R = $('#rgb #Red')
	$G = $('#rgb #Green')
	$B = $('#rgb #Blue')
	$H = $('#hsl #hue')
	$S = $('#hsl #saturation')
	$L = $('#hsl #luminosity')
}

function randomDude () {
	//picks a random color
	var randomR=Math.floor(Math.random()* 255);
	var randomG=Math.floor((Math.random()* 255));
	var randomB=Math.floor((Math.random()* 255));
	theColor.setRGB(randomR, randomG, randomB);
	$colorName.val(theColor.hex);
	setColor();
}

function setColor() {
	//sets up the color
	var userColor = $colorName.val().toLowerCase().replace(" ", "");
	for(var i = 0; i < basicColorNames.length; i++){
		//finds color name from basic color name array
		if(userColor == basicColorNames[i].color){
			userColor = basicColorNames[i].hex;
		}
	}
	 if(userColor[0] != '#'){
		//replace with HTML inject into readout display
		alert('Not a Valid Color;');
	 } else {
	  theColor.setHex(userColor);
	 //calibrate sliders
	 calRGBSliders();
	 calHSLSliders();
	 fillColor();
	}
}

function calRGBSliders(){
	// recalibrates the RGB sliders
	$R.slider( "value", theColor.r );
	$G.slider( "value", theColor.g );
	$B.slider( "value", theColor.b );
}

function calHSLSliders(){
	// recalibrates the HSL sliders
	$H.slider( "value", theColor.h);
	$S.slider( "value", theColor.s);
	$L.slider( "value", theColor.l);
}

function setRGB(){
	// retrieves RGB slider values
	var r = $R.slider("value");
	var g = $G.slider("value");
	var b = $B.slider("value");
	theColor.setRGB(r, g, b);
	calHSLSliders();
	$colorName.val(theColor.hex);
	fillColor();
}

function setHSL(){
	// retrieves HSL slider values
	var h = $('#hue').slider("value");
	var s = $('#saturation').slider("value");
	var l = $('#luminosity').slider("value");
	theColor.setHSL(h, s, l);
	calRGBSliders();
	$colorName.val(theColor.hex);
	fillColor();
}

function fillColor(){
	//auto-generates the 2-4 paired colors
	//sets autogenerated harmonic colors
	readOut();
	$('#chosen').css('background-color', theColor.hex);
	triLeft.setHSL(theColor.h - 120, theColor.s, theColor.l);
	triRight.setHSL(theColor.h + 120, theColor.s, theColor.l);
	//Lighter shade clipping
	if(theColor.l > 80) {
	   lighter.setHSL(theColor.h, theColor.s, 100);
	}else{
	  lighter.setHSL(theColor.h, theColor.s, theColor.l + 20);
	}
	//Darker shade clipping
	if(theColor.l < 20){
	    darker.setHSL(theColor.h + 180, theColor.s, 0);
	}else{
	    darker.setHSL(theColor.h, theColor.s, theColor.l - 20);
	}
	$('#triLeft').css('background-color', triLeft.hex);
	$('#triRight').css('background-color', triRight.hex);
	$('#lighter').css('background-color', lighter.hex);
	$('#darker').css('background-color', darker.hex);
	
	inject();
}

function readOut() {
  //Prints out the values and labels of sliders
	$('#readout p').text("Hue: " + Math.floor(theColor.h) + 
	" | Saturation: " + Math.floor(theColor.s) +
	" | Luminosity: " + Math.floor(theColor.l) + 
	" | (R: " + theColor.r + ", G: " + theColor.g + ", B: " 
	+ theColor.b + ")");
}

//associative array for basic colors to hex code
var basicColorNames = [
	{color: 'aliceblue', hex:'#F0F8FF'},
	{color: 'aqua', hex:'#00FFFF'},
	{color: 'azure', hex:'#F0FFFF'},
	{color: 'beige', hex:'#F5F5DC'},
	{color: 'black', hex:'#000000'},
	{color: 'blue', hex:'#0000FF'},
	{color: 'brown', hex:'#A52A52A'},
	{color: 'fuchsia', hex:'#FF00FF'},
	{color: 'gray', hex:'#808080'},
	{color: 'grey', hex:'#808080'},
	{color: 'green', hex:'#008000'},
	{color: 'lime', hex:'#00FF00'},
	{color: 'maroon', hex:'#800000'},
	{color: 'navy', hex:'#000080'},
	{color: 'olive', hex:'#808000'},
	{color: 'purple', hex:'#800080'},
	{color: 'red', hex:'#FF0000'},
	{color: 'silver', hex:'#C0C0C0'},
	{color: 'teal', hex:'#008080'},
	{color: 'white', hex:'#FFFFFF'},
	{color: 'yellow', hex:'#FFFF00'}
]

